import { readFileSync } from 'node:fs';
import { inflateSync } from 'node:zlib';

import { plotExtensionOf } from '../spec/classify.ts';
import { countPdfPagesInText, largestPageTreeCount, type PageCount } from './pdfPages.ts';
import { listZip, readZipEntry } from '../zip/zip.ts';

/**
 * How many pages a plot file has, without rendering it.
 *
 * Every "generate a layout from this folder" command needs this for dozens of
 * files at once, so converting each one to PDF just to count would make the
 * command unusable. Each format is counted from its own structure instead.
 *
 * The answer says how much it can be trusted. R's version guessed silently and
 * a wrong guess turned into missing rows in a workbook; here an estimate is
 * labelled, and the extension can say so.
 */
export { countPdfPagesInText, type PageCount } from './pdfPages.ts';

/** Count pages in a file on disk. */
export function countPages(filePath: string): PageCount {
  const extension = plotExtensionOf(filePath) ?? '';
  return countPagesIn(readFileSync(filePath), extension);
}

/** Count pages in bytes already in memory. */
export function countPagesIn(bytes: Buffer, extension: string): PageCount {
  switch (extension.toLowerCase()) {
    case 'pdf':
      return countPdfPages(bytes);
    case 'png':
      return { pages: 1, confidence: 'exact' };
    case 'pptx':
      return countPptxSlides(bytes);
    case 'docx':
      return countDocxPages(bytes);
    case 'html':
    case 'htm':
      return {
        pages: 1,
        confidence: 'estimated',
        reason: 'An HTML page is only paginated once a browser renders it.',
      };
    default:
      return { pages: 1, confidence: 'estimated', reason: `No page count is available for .${extension} files.` };
  }
}

// ------------------------------------------------------------------------- //
// PDF
// ------------------------------------------------------------------------- //


/**
 * Read the page count out of a PDF's page tree.
 *
 * The root of that tree carries `/Count`, so the largest count in the file is
 * the document's length. Files written since PDF 1.5 may hide the tree inside
 * compressed object streams, so if nothing is found in the clear, every
 * Flate-compressed stream is inflated and searched too.
 */
export function countPdfPages(bytes: Buffer): PageCount {
  const text = bytes.toString('latin1');
  const direct = countPdfPagesInText(text);
  if (direct.confidence === 'exact') return direct;

  for (const stream of inflateStreams(bytes)) {
    const nested = largestPageTreeCount(stream);
    if (nested !== undefined) return { pages: nested, confidence: 'exact' };
  }

  return direct;
}

/** Inflate every Flate-compressed stream, skipping any that will not inflate. */
function* inflateStreams(bytes: Buffer): Generator<string> {
  const text = bytes.toString('latin1');
  const marker = /stream\r?\n/g;

  for (let match = marker.exec(text); match !== null; match = marker.exec(text)) {
    const dictionary = text.slice(Math.max(0, match.index - 300), match.index);
    if (!dictionary.includes('/FlateDecode')) continue;

    const start = match.index + match[0].length;
    const end = text.indexOf('endstream', start);
    if (end === -1) continue;

    try {
      yield inflateSync(bytes.subarray(start, end)).toString('latin1');
    } catch {
      // Object streams can be encrypted or use predictors we do not unpack;
      // one unreadable stream is not a reason to give up on the file.
    }
  }
}

// ------------------------------------------------------------------------- //
// Office
// ------------------------------------------------------------------------- //

const SLIDE_PART = /^ppt\/slides\/slide\d+\.xml$/;

/** Slides are one part each, so a PowerPoint deck can be counted exactly. */
export function countPptxSlides(bytes: Buffer): PageCount {
  const slides = listZip(bytes).filter((entry) => SLIDE_PART.test(entry.name)).length;
  if (slides > 0) return { pages: slides, confidence: 'exact' };

  return { pages: 1, confidence: 'estimated', reason: 'This file has no slide parts. It may not be a .pptx.' };
}

/**
 * A Word document has no page count of its own — pages exist only once
 * something lays the text out. Word records the number it last saw in
 * `docProps/app.xml`, which is right whenever Word saved the file, and stale
 * or missing for a document generated by a script.
 */
export function countDocxPages(bytes: Buffer): PageCount {
  const properties = listZip(bytes).find((entry) => entry.name === 'docProps/app.xml');

  if (properties !== undefined) {
    const app = readZipEntry(bytes, 'docProps/app.xml')?.toString('utf8') ?? '';
    const pages = Number(/<Pages>(\d+)<\/Pages>/.exec(app)?.[1] ?? NaN);

    if (Number.isInteger(pages) && pages >= 1) {
      return pages >= 2
        ? { pages, confidence: 'exact' }
        : {
            pages,
            confidence: 'estimated',
            reason: 'Word reports one page, which is also what it reports for a document it has never laid out.',
          };
    }
  }

  return {
    pages: 1,
    confidence: 'estimated',
    reason: 'This document carries no page count. Open and save it in Word, or convert it, to get a real one.',
  };
}
