import * as vscode from 'vscode';

import { LAYOUT_FILE_SUFFIX } from '../../core/src/layout/layoutFile.ts';

/**
 * Where the extension puts what it makes.
 *
 * Everything project-scoped goes under `.plotexcel/` at the workspace root:
 * generated layouts, rendered workbooks, the last run's log. Pipeline
 * intermediates do not live here at all — they belong in the system temp
 * folder, because they are reproducible and there can be thousands of them.
 */

export const PLOTEXCEL_DIR = '.plotexcel';

/** A single `*` ignores every file beside it, including this file. */
const GITIGNORE = ['# Everything in this folder is generated by the plotExcel extension.', '*', ''].join('\n');

export interface ProjectPaths {
  readonly root: vscode.Uri;
  readonly base: vscode.Uri;
  readonly layouts: vscode.Uri;
  readonly out: vscode.Uri;
  readonly logs: vscode.Uri;
}

export function projectPaths(folder: vscode.WorkspaceFolder): ProjectPaths {
  const base = vscode.Uri.joinPath(folder.uri, PLOTEXCEL_DIR);
  return {
    root: folder.uri,
    base,
    layouts: vscode.Uri.joinPath(base, 'layouts'),
    out: vscode.Uri.joinPath(base, 'out'),
    logs: vscode.Uri.joinPath(base, 'logs'),
  };
}

/**
 * Create the folder if it is not there, with the .gitignore that hides it.
 *
 * Written lazily, on first use, and never by editing a file the user owns:
 * appending to their root .gitignore would be a change they did not ask for,
 * in a file they may have strong opinions about.
 */
export async function ensureProjectFolder(folder: vscode.WorkspaceFolder): Promise<ProjectPaths> {
  const paths = projectPaths(folder);

  for (const directory of [paths.base, paths.layouts, paths.out, paths.logs]) {
    await vscode.workspace.fs.createDirectory(directory);
  }

  const ignore = vscode.Uri.joinPath(paths.base, '.gitignore');
  try {
    await vscode.workspace.fs.stat(ignore);
  } catch {
    await vscode.workspace.fs.writeFile(ignore, Buffer.from(GITIGNORE, 'utf8'));
  }

  return paths;
}

/** The workspace folder a file belongs to, or the only one open. */
export function folderFor(uri?: vscode.Uri): vscode.WorkspaceFolder | undefined {
  if (uri !== undefined) {
    const owner = vscode.workspace.getWorkspaceFolder(uri);
    if (owner !== undefined) return owner;
  }

  const folders = vscode.workspace.workspaceFolders ?? [];
  return folders.length === 1 ? folders[0] : undefined;
}

/**
 * Ask which folder to use, when a command cannot tell on its own.
 *
 * Only ever reached in a multi-root workspace with no file to go on; the
 * answer is remembered for the session so it is asked once, not every time.
 */
let rememberedFolder: vscode.WorkspaceFolder | undefined;

export async function chooseFolder(uri?: vscode.Uri): Promise<vscode.WorkspaceFolder | undefined> {
  const direct = folderFor(uri);
  if (direct !== undefined) return direct;

  const folders = vscode.workspace.workspaceFolders ?? [];
  if (folders.length === 0) {
    void vscode.window.showWarningMessage(
      'plotExcel needs an open folder. Use File > Open Folder, then try again.',
    );
    return undefined;
  }

  if (rememberedFolder !== undefined && folders.includes(rememberedFolder)) return rememberedFolder;

  const picked = await vscode.window.showWorkspaceFolderPick({ placeHolder: 'Which folder should plotExcel use?' });
  if (picked !== undefined) rememberedFolder = picked;
  return picked;
}

/** A name that cannot collide with an existing layout, derived from a source. */
export async function layoutUriFor(paths: ProjectPaths, name: string): Promise<vscode.Uri> {
  const stem = name.replace(/[^A-Za-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'plots';

  for (let attempt = 0; ; attempt += 1) {
    const candidate = vscode.Uri.joinPath(paths.layouts, `${stem}${attempt === 0 ? '' : `-${attempt}`}${LAYOUT_FILE_SUFFIX}`);
    try {
      await vscode.workspace.fs.stat(candidate);
    } catch {
      return candidate;
    }
  }
}

/** Where a layout's workbook goes when the layout does not say. */
export function defaultOutputFor(paths: ProjectPaths, layoutName: string): vscode.Uri {
  const stem = layoutName.replace(new RegExp(`${LAYOUT_FILE_SUFFIX.replace(/\./g, '\\.')}$`, 'i'), '');
  return vscode.Uri.joinPath(paths.out, `${stem || 'plots'}.xlsx`);
}
