#!/usr/bin/env Rscript
#
# Produce the reference workbook the TypeScript port is measured against.
#
#     Rscript tools/make-reference-workbook.R
#
# Writes, next to itself:
#
#   reference.xlsx           the workbook, straight from the R package
#   reference.plotexcel.tsv  the same table in the port's layout format
#
# Column widths, row heights and image sizes in reference.xlsx are the numbers
# P0 has to reproduce. Keep both files together: the .tsv is the input, the
# .xlsx is the expected output, and neither means much alone.

library(plotExcel)
library(data.table)

outDir <- tryCatch(dirname(sys.frame(1)$ofile), error = function(e) ".")
if (is.null(outDir) || is.na(outDir)) outDir <- "."

example <- function(name) system.file(file.path("exampleData", name), package = "plotExcel")

# The table from ?plotExcel, with an explicit resolution so the port has a
# number to match rather than a default that might drift.
d <- data.table(
  Description = c("Crop::3", "Text rotated up::4", "Full page::vcenter"),
  `Plots 1` = c(
    paste0(example("01-Iris.pdf"), "::xmax 85::resolution 150"),
    paste0(example("04-IrisMulti.pdf"), "::page 2::resolution 150"),
    paste0(example("02-Iris-Brewer.pdf"), "::resolution 150")
  ),
  `Plots 2` = c(
    paste0(example("02-Iris-Brewer.pdf"), "::resolution 150"),
    paste0(example("04-IrisMulti.pdf"), "::page 1::resolution 150"),
    paste0(example("03-Iris-scale2.pdf"), "::resolution 150")
  ),
  Comparison = rep("diff(`Plots 1`, `Plots 2`)", 3)
)

xlsx <- file.path(outDir, "reference.xlsx")
plotExcel(
  d,
  filename = xlsx,
  headerRowStyle = "center",
  FLAGaddBorders = FALSE,
  FLAGpdf = FALSE,
  textColWidth = 5
)

# Same table, written in the layout format the extension reads. Paths are kept
# absolute here because the example files live inside the installed package.
tsvLines <- c(
  "# Reference table for the VS Code port. Generated by tools/make-reference-workbook.R.",
  "#resolution: 150",
  "#textColWidth: 5",
  "#headerRowStyle: center",
  paste(names(d), collapse = "\t"),
  apply(d, 1, function(row) paste(row, collapse = "\t"))
)
writeLines(tsvLines, file.path(outDir, "reference.plotexcel.tsv"))

message("Wrote reference.xlsx and reference.plotexcel.tsv to ", normalizePath(outDir))
message("Both files are inputs to the P0 geometry spike - keep them together.")
